src/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :posts do
    resources :songs, only: %i(create)
  end
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_one_attached :song
  default_scope -> { order(created_at: :desc) }
  validates :caption, presence: true
  validates :profile,  length: { maximum: 255 }
end

src/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :profile,  length: { maximum: 255 }

  has_many :posts, dependent: :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインをしてください"
      redirect_to login_url
    end
  end
end

src/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update,:destroy]
  before_action :correct_user,   only: [:edit, :update,:destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.song.attach(params[:post][:song])
    if @post.song.present?
      @post.save
      redirect_to root_path
      flash[:success] = "楽曲が投稿されました"
    else
      redirect_to root_path
      flash[:danger] = "投稿に失敗しました"
    end
  end

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "楽曲情報を更新しました"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "楽曲を削除しました"
    redirect_to request.referrer || root_url
  end

  private
    def post_params
      params.require(:post).permit(:caption,:song,:profile).merge(user_id: current_user.id)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end

end

src/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_back_or user
    else
      flash.now[:danger] = 'メールアドレスまたはパスワードが違います'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

src/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "MUSIC-FACTORYへようこそ"
      redirect_to @user
    else
      render 'new'
    end
  end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = "プロフィールを更新しました"
        redirect_to @user
      else
        render 'edit'
      end
    end

    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
    end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation,:profile)
    end



    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/posts_helper.rb
module PostsHelper
end

src/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

src/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

src/app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

src/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Muon-Factory by Yuto Hamada
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

src/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
			<button data-toggle="collapse-side" data-target=".side-collapse" data-target-2=".side-collapse-container" type="button" class="navbar-toggle pull-left">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "muon-factory", root_path, id: "logo" %>
		<div class="navbar-inverse side-collapse in">
			<nav role="navigation" class="navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "BGM", posts_path %></li>
        <li><%= link_to "作曲家", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <li><%= link_to "マイページ", current_user %></li>
            <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
            <li>
            <%= link_to "投稿", new_post_path %>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  </div>
</header>

<script type="text/javascript">
	$(document).ready(function() {
	var sideslider = $('[data-toggle=collapse-side]');
	var sel = sideslider.attr('data-target');
	var sel2 = sideslider.attr('data-target-2');
	sideslider.click(function(event){
		$(sel).toggleClass('in');
		$(sel2).toggleClass('out');
	});
	});
</script>

src/app/views/layouts/_header_html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muon-Factory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
  <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

src/app/views/posts/_post.html.erb
<li id="micropost-<%= post.id %>">
<%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user">作曲者: <%= link_to post.user.name, post.user %></span>
  <span class="content">曲名: <%= link_to post.caption, (post_path(post)) %></span>
  <div class="song">
  <%= audio_tag url_for(post.song), controls: true %>
  <%= link_to "ダウンロード", (post.song) %>

    <% if current_user?(post.user) %>
      <%= link_to "削除", post, method: :delete,
                                       data: { confirm: "削除してもいいですか?" } %>
    <% end %>
  </div>
</li>

src/app/views/posts/edit.html.erb
<h1>楽曲情報を変更</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @post, local: true) do |f| %>
      <%= f.label :caption, "タイトル" %>
      <%= f.text_field :caption %>
      <%= f.label :profile, "曲紹介" %>
      <%= f.text_area :profile %>
        <%= f.file_field :song, accept: "song/mp3,song/wav,song/mpeg" %>
      <%= f.submit "投稿", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

src/app/views/posts/index.html.erb
<h1>BGM一覧</h1>
      <ol class="microposts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>

src/app/views/posts/new.html.erb
<h1>楽曲登録</h1>
<%= form_with(model: @post, local: true) do |f| %>
  <%= f.label :caption, "タイトル" %>
  <%= f.text_field :caption %>
  <%= f.label :profile, "曲紹介" %>
  <%= f.text_area :profile %>
    <%= f.file_field :song, accept: "song/mp3,song/wav,song/mpeg" %>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

src/app/views/posts/show.html.erb
<h1>この楽曲について</h1>
<%= link_to gravatar_for(@post.user, size: 50), @post.user %>
  <span class="user"><%= link_to @post.user.name, @post.user %></span>
  <span class="content"><%= link_to @post.caption, (post_path(@post)) %></span>
  <div class="song">
  <%= audio_tag url_for(@post.song), controls: true %>
  <%= link_to "ダウンロード", (@post.song) %>

    <% if current_user?(@post.user) %>
    <%= link_to "削除", @post, method: :delete,
    data: { confirm: "削除してもいいですか?" } %>
    <%= link_to "楽曲情報を編集", edit_post_path(current_user), class: "edit-post btn btn-outline-dark common-btn edit-profile-btn" %>
    <% end %>

  <h2 class="post-profile">
  <%= @post.profile %>
  </h2>
  </div>

src/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

src/app/views/static_pages/about.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
<div class="container-fluid py-5">
  <h1 class="display-5 fw-bold">このサイトの音楽は無料で使えます</h1>
  <p class="col-md-8 fs-4">個人で利用される方や商用で利用される方も報告なしでお使いいただけます。</p>
  <p class="col-md-8 fs-4">ご利用の際の著作権・提供等の表示は不要ですが、音源の権利は当該音源の作曲・制作者が保持しています。</p>
  <p class="col-md-8 fs-4">作曲・制作者名の偽称を問わず、非権利者が当サイトの音源を二次的に公開・配布する行為は禁止とさせていただきます。</p>
</div>
</div>

<div class="row align-items-md-stretch">
<div class="col-md-6">
  <div class="h-100 p-5 text-white bg-dark rounded-3">
    <h2 class="About">クリエイターの方へ</h2>
    <p>自由にご自身の楽曲を投稿することができます。ただし以下の条件を満たしていることを条件に投稿してください。</p>
    <ul>
     <li>音源の著作権、著作者人格権、著作隣接権を含む一切の権利を保有していること</li>
     <li>音源について、特定の音楽出版社、レコード会社、プロダクション（制作会社）、著作権管理団体等との専属作家契約、著作権譲渡契約、および管理代行契約等を締結していないこと</li>
     <li>既存の楽曲をカバー・アレンジした音源を公開する場合、元となった楽曲の著作権がすでに消滅しており、パブリック・ドメインに属していること</li>
     <li>音源に対して、第三者に権利を譲渡しておらず、また、独占的に利用許諾を設定していないこと</li>
     <li>その他、当サイトを通じて当ライセンスに基づき音源を提供、公開、および素材としてユーザーに使用を許諾することに一切の支障がないこと</li>
    </ul>
  </div>
</div>
<div class="col-md-6">
  <div class="h-100 p-5 bg-light border rounded-3">
    <h2 class="About">このサイトの思い</h2>
    <p>昨今Youtuberが流行る中で無料で使えるBGMを配布しているサイトが少なく、動画配信者の方に選択肢を増やしてあげられればと思い製作しました。
    また自分の曲を聴いてもらう機会があまりない方でも、自由に投稿できればいいなと思い、曲をアップロードできる環境を作っております。</p>
  </div>
</div>
</div>

src/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>MUON-FACTORYへようこそ</h1>

  <p>
    こちらは無料でBGMをダウンロードできるサイトです。
  </p>
 <p>クリエイターとしてBGMを投稿したい方は会員登録をしてください</p>

  <%= link_to "登録はこちら!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

src/app/views/users/edit.html.erb
<h1>プロフィールを編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "クリエイター名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "もう一度パスワードをお願いします" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :profile, "自己紹介" %>
      <%= f.text_area :profile %>

      <%= f.submit "変更を適応する", class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

src/app/views/users/index.html.erb
<h1>作曲家</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <div class="users-name">
      <%= link_to user.name, user %>
      </div>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

src/app/views/users/new.html.erb
<h1>クリエイター登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name, "クリエイター名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "もう一度パスワードをお願いします" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "アカウントを作成", class: "btn btn-primary" %>
    <% end %>
    <p>アカウントをお持ちですか? <%= link_to "ログインはこちら", login_path %></p>
  </div>
</div>

src/app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
  <section class="user_info">
  <h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
  </h1>
  <section class="user-profile">
  <%= @user.profile %>
  </section>
  <p>
  <% if @user == current_user %>
  <div class="edit">
  <%= link_to "プロフィールを編集", edit_user_path(current_user), class: "btn btn-outline-dark common-btn edit-profile-btn" %>
  </div>
  <% end %>
  </p>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.posts.any? %>
      <h3>楽曲一覧</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>